version: "2"

services:
  frontend:
    image: rsvpfoxbot-frontend:latest
    build: .
    ports:
    - 5000:80
    environment:
    - INFLUX_HOST=influxdb
    depends_on:
    - "influxdb"

  influxdb:
    image: influxdb:1.8
    volumes:
    - influxdb-storage:/var/lib/influxdb
    ports:
    - "8086:8086"

volumes:
  influxdb-storage:
